### ISSUE TITLE
Github link in ie explorer

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest#31]
The OPen Forest github link is often shared with USFS staff which use ie explorer by default.  When opening in ie explorer.  The very useful left side  boxes with links to other parts of the wiki can;t be seen.  Unless it is my browser setting causing the problem.  I'll have other test as well.

**Comment by hannahkane** [comment]
Can you include a screenshot, please? Thank you!

**Comment by aaronburk** [comment]
![image](https://user-images.githubusercontent.com/25828899/46171851-c3fb8800-c26f-11e8-9bc7-ed786ad92b66.png)
Yes sorry about that I thought I did.  I tested with other FS users today and got same result at 100% zoom (works fine in Chrome

**Comment by aaronburk** [comment]
I know github no longer supprts ie explorer that may be the issue??

**Comment by lauraGgit** [comment]
There might not be much we can do about this as this is about Github, we could add sidebar links to the bottom of the main page.

**Comment by davemcorwin** [comment]
@aaronburk can this be closed?

**Comment by aaronburk** [comment]
yes I will close
